version: "3.7"

services:

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: evkk
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
