version: "3.7"

services:

  postgres:
    image: postgres:11
    volumes:
      - ./setup/postgres/init:/docker-entrypoint-initdb.d
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:5.0.6
    ports:
      - 6379:6379
