FROM node:16-alpine AS ui-builder
COPY ./ui /app
RUN cd /app && yarn install && yarn build

FROM node:16-alpine AS ui
RUN yarn global add http-server@13.0.2
COPY --from=ui-builder /app/build /app/ui

EXPOSE 8080
WORKDIR /app/ui/
CMD ["http-server"]
