version: "3.7"

services:

  caddy:
    image: caddy:2.4.5-alpine
    container_name: evkk-caddy
    profiles: [ "all", "backend" ]
    restart: always
    ports:
      - "9999:9999"
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  local_ui_builder:
    container_name: evkk-local-ui-builder
    profiles: [ "all", "ui" ]
    restart: always
    build:
      context: .
      dockerfile: docker/local/evkk-local-ui-builder.Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./ui:/app
    ports:
      - "3000:3000"

  postgres:
    image: postgres:13-alpine
    container_name: evkk-postgres
    profiles: [ "all", "backend" ]
    restart: always
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: evkk
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    container_name: evkk-redis
    profiles: [ "all", "backend" ]
    restart: always
    ports:
      - "6379:6379"

  stanza-server:
    container_name: evkk-stanza-server
    profiles: [ "all", "stanza" ]
    restart: always
    build:
      context: .
      dockerfile: docker/images/evkk-stanza-server.Dockerfile
    ports:
      - "5300:5300"

  klasterdaja:
    container_name: evkk-klasterdaja
    profiles: [ "all", "klasterdaja" ]
    restart: always
    build:
      context: .
      dockerfile: docker/images/evkk-klasterdaja.Dockerfile
    ports:
      - "5100:5100"

  corrector-server:
    container_name: evkk-corrector-server
    profiles: [ "all", "corrector" ]
    restart: always
    build:
      context: .
      dockerfile: docker/images/evkk-corrector-server.Dockerfile
    ports:
      - "5200:5200"
