version: "3.7"

services:

  postgres:
    image: postgres:13-alpine
    container_name: evkk-postgres
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: evkk
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    container_name: evkk-redis
    ports:
      - "6379:6379"

  stanza-server:
    container_name: evkk-stanza-server
    build:
      context: .
      dockerfile: docker/images/evkk-stanza-server.Dockerfile
    ports:
      - "5000:5000"

  #klasterdaja:
  #  container_name: evkk-klasterdaja
  #  build:
  #    context: .
  #    dockerfile: docker/images/evkk-klasterdaja.Dockerfile
  #  ports:
  #    - "5100:5100"
