version: "3.7"

services:

  postgres:
    image: postgres:13-alpine
    container_name: evkk-postgres
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: evkk
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    container_name: evkk-redis
    ports:
      - "6379:6379"

  stanza:
    container_name: evkk-stanza
    build:
      context: .
      dockerfile: ./docker/images/Dockerfile.stanza
    ports:
      - "5000:5000"
