FROM ubuntu:20.04
SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get install wget openjdk-11-jdk -y
RUN wget --no-verbose https://repo.anaconda.com/archive/Anaconda3-2021.05-Linux-x86_64.sh && chmod +x ./Anaconda3-2021.05-Linux-x86_64.sh
RUN ./Anaconda3-2021.05-Linux-x86_64.sh -b -p ~/anaconda3 && rm ./Anaconda3-2021.05-Linux-x86_64.sh
ENV PATH=~/anaconda3/bin:$PATH
RUN conda install -c estnltk -c conda-forge estnltk=1.6.9b
