common_lemmas = ['olema', 'ja', 'see', 'tema', 'mina', 'ei', 'et', 'kui', 'mis', 'ka', 'saama', 'ning', 'oma', 'aga',
                 'sina', 'pidama', 'siis', 'või', 'kes', 'aasta', 'võima', 'üks', 'nii', 'ise', 'tulema', 'tegema',
                 'kõik', 'teine', 'ütlema', 'nagu', 'minema', 'kuid', 'inimene', 'aeg', 'teadma', 'veel', 'jääma',
                 'võtma', 'kas', 'andma', 'välja', 'juba', 'vaid', 'mitte', 'miski', 'hakkama', 'suur', 'mees',
                 'nägema', 'sest', 'palju', 'kaks', 'tahtma', 'kus', 'uus', 'üle', 'pärast', 'kord', 'mõni', 'esimene',
                 'sõna', 'ära', 'selline', 'väga', 'rääkima', 'küll', 'enam', 'nüüd', 'töö', 'ainult', 'iga', 'leidma',
                 'laps', 'vastu', 'asi', 'kasutama', 'vaatama', 'naine', 'panema', 'mingi', 'ju', 'kuidas', 'kõige',
                 'eest', 'sama', 'tundma', 'hea', 'käsi', 'päev', 'mõtlema', 'viimane', 'keegi', 'ega', 'riik', 'peale',
                 'arvama', 'juht', 'osa', 'käima', 'elu', 'kohta', 'kogu', 'jõudma', 'erinev', 'siin', 'seal', 'rohkem',
                 'tooma', 'läbi', 'tagasi', 'näide', 'keel', 'silm', 'just', 'võimalik', 'mitu', 'ette', 'isegi',
                 'vahel', 'ikka', 'siiski', 'ehk', 'kolm', 'enne', 'suurem', 'kroon', 'alla', 'kokku', 'maailm',
                 'tulemus', 'poolt', 'isik', 'koht', 'võimalus', 'küsima', 'küsimus', 'puhul', 'pool', 'muu', 'samuti',
                 'näitama', 'kirjutama', 'pea', 'mõte', 'koos', 'elama', 'praegu', 'oluline', 'raha', 'linn', 'kuni',
                 'kuigi', 'väike', 'viima', 'toimuma', 'suutma', 'muutuma', 'miks', 'maa', 'jätma', 'eriti', 'ema',
                 'kuna', 'lugema', 'lõpp', 'alus', 'järgmine', 'tee', 'õigus', 'probleem', 'laskma', 'ootama', 'vana',
                 'esitama', 'järgi', 'siduma', 'juurde', 'all', 'jaoks', 'tekkima', 'nimetama', 'viis', 'kohe',
                 'andmed', 'kodu', 'nimi', 'edasi', 'isa', 'kuulma', 'ees', 'põhjus', 'vastama', 'poole', 'parem',
                 'tähendama', 'tegemine', 'püüdma', 'eesmärk', 'lihtsalt', 'seisma', 'maja', 'noor', 'maha', 'istuma',
                 'pakkuma', 'alati', 'korral', 'maksma', 'alles', 'lisa', 'miljon', 'vaja', 'seega', 'sõitma',
                 'tegevus', 'kunagi', 'üles', 'muidugi', 'looma', 'tegelikult', 'üldse', 'lubama', 'hetk', 'sisse',
                 'aru', 'nägu', 'samas', 'kaasa', 'pikk', 'hoidma', 'jooksul', 'poiss', 'kool', 'hästi', 'kuuluma',
                 'rahvas', 'milline', 'arv', 'kohalik', 'oskama', 'keskmine', 'kinnitama', 'algus', 'juures', 'liige',
                 'auto', 'olukord', 'vähemalt', 'valima', 'too', 'kinni', 'nädal', 'raamat', 'tabel', 'aitama',
                 'tüdruk', 'paar', 'raske', 'esinema', 'väärtus', 'ent', 'mõju', 'ilma', 'kuu', 'hiljem', 'tunduma',
                 'kindel', 'töötama', 'võrdlema', 'liiga', 'mõlema', 'õige', 'seadus', 'ümber', 'tõusma', 'uks',
                 'lisama', 'astuma', 'uurima', 'otsustama', 'vanem', 'saatma', 'neli', 'vesi', 'meel', 'kandma',
                 'varem', 'uskuma', 'ajama', 'huvi', 'asuma', 'jutt', 'tõttu', 'kasutamine', 'ilmselt', 'tekst',
                 'otsima', 'mängima', 'tund', 'süsteem', 'ülikool', 'hääl', 'lugu', 'jalg', 'uuring', 'jälle',
                 'vajalik', 'nõudma', 'muutma', 'algama', 'hoopis', 'ilmuma', 'kutsuma', 'suhtes', 'kindlasti', 'kaudu',
                 'taga', 'suhe', 'mõistma', 'vajadus', 'juhtuma', 'otsus', 'lahti', 'autor', 'ostma', 'kaduma',
                 'kolmas', 'vähem', 'sort', 'valitsus', 'peaaegu', 'õhtu', 'kasvama', 'soovima', 'lööma', 'selge',
                 'täis', 'joonis', 'umbes', 'mööda', 'teatama', 'arst', 'määrama', 'vastav', 'kell', 'töötaja', 'jah',
                 'päris', 'president', 'sajand', 'arvestama', 'lõpuks', 'seisukoht', 'alustama', 'täna', 'vist',
                 'avama', 'niisugune', 'eile', 'tuba', 'tõstma', 'eestlane', 'juriidiline', 'ühiskond', 'tõesti',
                 'üsna', 'tänav', 'sinna', 'täiesti', 'areng', 'õpetaja', 'tohtima', 'hind', 'hindama', 'patsient',
                 'paistma', 'märkima', 'lõpetama', 'kõrge', 'pilt', 'õppima', 'järele', 'eelmine', 'tase', 'firma',
                 'ettevõte', 'kuhu', 'meeldima', 'selg', 'terve', 'kiri', 'valge', 'ometi', 'vastavalt', 'avaldama',
                 'vastus', 'hulk', 'kümme', 'analüüs', 'olev', 'laud', 'sõber', 'selguma', 'pilk', 'tunnistama',
                 'ajalugu', 'puuduma', 'lootma', 'hinnang', 'seetõttu', 'täitma', 'mõjutama', 'surema', 'protsent',
                 'moodustama', 'seos', 'mäng', 'tõmbama', 'selgitama', 'võimaldama', 'väiksem', 'kohaselt', 'ajal',
                 'kõrval', 'piir', 'tähendus', 'jumal', 'sööma', 'liikuma', 'tähelepanu', 'tekitama', 'suu', 'vajama',
                 'parim', 'väitma', 'muutus', 'teema', 'hommik', 'pigem', 'tegu', 'kohus', 'kirjeldama', 'sotsiaalne',
                 'nõukogu', 'eelkõige', 'abil', 'õpilane', 'ülesanne', 'praegune', 'mõiste', 'surm', 'tugev',
                 'artikkel', 'kahju', 'märkama', 'must', 'valmis', 'paluma', 'ikkagi', 'ilus', 'haige', 'kaotama',
                 'ravi', 'projekt', 'abi', 'teadmine', 'kartma', 'film', 'sõltuma', 'haigus', 'ruum', 'näiteks',
                 'uurimus', 'taas', 'sageli', 'veidi', 'järel', 'süda', 'korraldama', 'meetod', 'langema', 'vähe',
                 'protsess', 'vaba', 'täpselt', 'punkt', 'erinevus', 'materjal', 'sündima', 'enamik', 'katse', 'õhk',
                 'kõrgem', 'taim', 'sattuma', 'kuidagi', 'ligi', 'tingimus', 'seni', 'võitma', 'pank', 'endine',
                 'asjaolu', 'aken', 'mets', 'poeg', 'mäletama', 'hulgas', 'roll', 'ainus', 'tegelema', 'politsei',
                 'loom', 'pääsema', 'lõppema', 'oluliselt', 'müüma', 'käsitlema', 'sealt', 'kirik', 'valik',
                 'tavaliselt', 'ärama', 'eks', 'rida', 'jätkama', 'tunne', 'rahvusvaheline', 'organisatsioon', 'jõud',
                 'kiiresti', 'toetama', 'kujutama', 'kuulama', 'kust', 'vorm', 'leping', 'põhjal', 'magama', 'naerma',
                 'natuke', 'pere', 'võib-olla', 'üksnes', 'poliitiline', 'jagama', 'idee', 'nõue', 'mudel', 'uurimine',
                 'kirjandus', 'tühi', 'punane', 'siia', 'käesolev', 'tulevik', 'hing', 'suhteliselt', 'kohustus',
                 'minut', 'juhtima', 'meenutama', 'lihtne', 'pöörama', 'kujunema', 'ehitama', 'näima', 'programm',
                 'uuesti', 'sobima', 'kultuur', 'jooksma', 'reegel', 'muidu', 'lahkuma', 'tüüp', 'konkreetne',
                 'põhjustama', 'võim', 'otsa', 'mööduma', 'ala', 'keskkond', 'esindaja', 'samm', 'tähtis', 'peal',
                 'seejärel', 'küla', 'õnn', 'võõras', 'muusika', 'suvi', 'arvuti', 'viga', 'näitaja', 'klient',
                 'õnnestuma', 'ringi', 'kogemus', 'vastutus', 'asemel', 'sellepärast', 'loomulikult', 'kõrvale', 'keha',
                 'käitumine', 'liit', 'toime', 'tuttav', 'sõda', 'sisaldama', 'suurim', 'vahele', 'teenus', 'üldine',
                 'saavutama', 'jooma', 'viskama', 'funktsioon', 'loomine', 'korter', 'ehkki', 'määr', 'osalema',
                 'lähtuma', 'omavalitsus', 'lausuma', 'avalik', 'puu', 'külm', 'kuus', 'tavaline', 'tagama',
                 'positiivne', 'pisut', 'suurenema', 'soov', 'enamasti', 'vald', 'äkki', 'lausa', 'sarnane', 'huvitav',
                 'jälgima', 'lehm', 'periood', 'plaan', 'turg', 'seletama', 'amet', 'laul', 'omanik', 'otse',
                 'armastama', 'osutuma', 'esimees', 'põhimõte', 'öö', 'sein', 'muld', 'kiire', 'seadma', 'käigus',
                 'lahendus', 'osas', 'vend', 'sundima', 'vahend', 'struktuur', 'rühm', 'tuhat', 'heitma', 'teenima',
                 'halb', 'paremini', 'kasv', 'koguma', 'leiduma', 'palk', 'nõnda', 'unustama', 'elanik', 'tunnus',
                 'viitama', 'soovitama', 'arvamus', 'kvaliteet', 'alates', 'teater', 'sees', 'kuju', 'seas', 'kukkuma',
                 'justkui', 'suurus', 'üritama', 'nimelt', 'mil', 'esile', 'armastus', 'peamine', 'grupp', 'tänu',
                 'puhas', 'leht', 'ühine', 'eriline', 'toetus', 'sündmus', 'koostöö', 'kaua', 'vähendama', 'üksik',
                 'märk', 'teade', 'rõhutama', 'haarama', 'suunama', 'informatsioon', 'kõne', 'tihti', 'klass',
                 'kohtumine', 'haigla', 'veelgi', 'kirjanik', 'omadus', 'saabuma', 'kaitsma', 'jätkuma', 'madal',
                 'lause', 'soe', 'pöörduma', 'foto', 'päike', 'peamiselt', 'tegur', 'piirkond', 'haridus', 'tõsi',
                 'kavatsema', 'no', 'analüüsima', 'teos', 'valmistama', 'sisu', 'veri', 'vähenema', 'hulka', 'lükkama',
                 'ettepanek', 'algul', 'piim', 'hoone', 'süü', 'perekond', 'objekt', 'venelane', 'valdkond', 'seoses',
                 'kokkulepe', 'tütar', 'taha', 'tänapäev', 'järgnema', 'korraga', 'varasem', 'juhataja', 'variant',
                 'vanus', 'liikumine', 'allikas', 'riiklik', 'üha', 'paik', 'piisavalt', 'noh', 'senine', 'kontrollima',
                 'sada', 'olemasolu', 'koostama', 'ajaleht', 'alt', 'kasu', 'talu', 'tõeline', 'huvitama', 'suund',
                 'külg', 'voodi', 'tagajärg', 'eraldi', 'õpetama', 'koer', 'koguni', 'rakendama', 'valimine', 'kestma',
                 'vahe', 'tervis', 'kontekst', 'vahetama', 'lühike', 'riigikogu', 'juuli', 'meeskond', 'kasutus',
                 'vabariik', 'tasuma', 'hindamine', 'komme', 'väide', 'valgus', 'mai', 'ületama', 'kevad', 'õlg',
                 'sisaldus', 'tükk', 'juhatus', 'tõepoolest', 'helistama', 'taevas', 'number', 'puudutama', 'võibolla',
                 'paber', 'liik', 'isiklik', 'ilm', 'võrra', 'eri', 'katma', 'rakendamine', 'avastama', 'oht',
                 'tegutsema', 'suurendama', 'kodanik', 'tabama', 'tuli', 'proovima', 'aine', 'küllap', 'ilmnema',
                 'seepärast', 'kohale', 'laev', 'element', 'sügis', 'meeter', 'jaanuar', 'vokaal', 'vedama', 'pidevalt',
                 'loobuma', 'kurat', 'seisund', 'igasugune', 'üksteise', 'levima', 'kuuluv', 'meri', 'keerama', 'ammu',
                 'vähene', 'kallis', 'hirm', 'tuul', 'tarvis', 'kerge', 'majanduslik', 'iseenese', 'eeldama',
                 'tegelane', 'poolest', 'suruma', 'september', 'saamine', 'dokument', 'juus', 'tapma', 'info', 'kõrv',
                 'vaatlema', 'igaüks', 'siit', 'summa', 'varsti', 'pikem', 'omavahel', 'omakorda', 'negatiivne',
                 'kaitse', 'kostma', 'kohal', 'ülevaade', 'arenema', 'laulma', 'kuluma', 'tingima', 'lendama',
                 'iseloomustama', 'mõjuma', 'osakaal', 'kokkuvõte', 'vaheline', 'sissetulek', 'kehtima', 'käsitlus',
                 'arve', 'tänavu', 'pealegi', 'täitmine', 'vara', 'esialgu', 'lootus', 'asuv', 'ulatus', 'mure', 'võit',
                 'pealt', 'loodus', 'mõnikord', 'eristama', 'kohtuma', 'igatahes', 'piirama', 'mainima', 'vanaema',
                 'teooria', 'otsene', 'sõnama', 'seitse', 'seesama', 'üksi', 'olulisem', 'kontroll', 'püsima',
                 'tööandja', 'käsk', 'internet', 'kuulutama', 'vale', 'julgema', 'teineteise', 'juuni', 'kaheksa',
                 'vastane', 'riie', 'osakond', 'seejuures', 'naeratama', 'peaminister', 'madalam', 'tõsine', 'noormees',
                 'tegelik', 'kasutaja', 'tasu', 'keelama', 'tähtsus', 'aprill', 'nähtus', 'ravim', 'märts', 'uni',
                 'norm', 'lugeja', 'oktoober', 'sulgema', 'hobune', 'hall', 'õde', 'järjest', 'füüsiline', 'varjama',
                 'sõlmima', 'noorem', 'kivi', 'kõigepealt', 'pärit', 'värv', 'august', 'tasand', 'näitleja',
                 'kusjuures', 'hoolimata', 'toit', 'tõenäoliselt', 'sobiv', 'oskus', 'linnavalitsus', 'arutama', 'ots',
                 'elav', 'põhjendama', 'täielik', 'jõgi', 'tagant', 'väljendama', 'millal', 'abikaasa', 'nina', 'kunst',
                 'neljas', 'vahepeal', 'kõlama', 'nahk', 'mood', 'püsti', 'romaan', 'edaspidi', 'vältima', 'järeldus',
                 'peremees', 'põlema', 'üliõpilane', 'parandama', 'etendus', 'tähistama', 'printsiip', 'kilomeeter',
                 'leppima', 'partei', 'erinema', 'viibima', 'detsember', 'omama', 'ametnik', 'instituut', 'võistlus',
                 'professor', 'keskmiselt', 'järgnev', 'üldiselt', 'puudumine', 'osutama', 'kiirus', 'lava', 'ühendama',
                 'majandus', 'positsioon', 'tunduvalt', 'tervik', 'telefon', 'kaup', 'samasugune', 'aspekt', 'dollar',
                 'risk', 'kael', 'publik', 'kinnitus', 'volikogu', 'lai', 'sõrm', 'paraku', 'pime', 'rahvuslik',
                 'taust', 'aktsia', 'saatus', 'vaataja', 'poliitika', 'direktor', 'tänane', 'tõestama', 'kõnelema',
                 'veebruar', 'kusagil', 'praktika', 'kunstnik', 'kiitma', 'keskus', 'omandama', 'eelistama',
                 'kehtestama', 'ühendus', 'köök', 'joon', 'ühtlasi', 'saar', 'lähedal', 'kasutatav', 'fakt',
                 'vaatamata', 'nurk', 'pruukima', 'november', 'valu', 'meelest', 'erinevalt', 'valitsema', 'tahe',
                 'uurija', 'ajakirjanik', 'ulatuma', 'seis', 'mulje', 'puutuma', 'pidu', 'lavastus', 'kaart', 'segama',
                 'loomulik', 'avaldus', 'toimuv', 'niisama', 'müük', 'koosnema', 'põrand', 'täht', 'toimima', 'saak',
                 'normaalne', 'rõõm', 'põhi', 'rõhk', 'selts', 'kahjuks', 'määramine', 'maakond', 'õppimine', 'aina',
                 'pind', 'selgelt', 'juhtimine', 'taipama', 'sugugi', 'mõõtma', 'juhtum', 'klubi', 'korralik', 'eeldus',
                 'komponent', 'vabadus', 'komisjon', 'niisiis', 'imelik', 'endiselt', 'püha', 'kuhugi', 'suhtumine',
                 'põlvkond', 'kasvatama', 'tähtsam', 'nõus', 'kannatama', 'talv', 'mälestus', 'lahendama', 'kahtlus',
                 'pood', 'võimatu', 'võimalikult', 'rind', 'tõus', 'vajuma', 'keeruline', 'seekord', 'buss', 'näitus',
                 'erakond', 'rahul', 'vari', 'vaevalt', 'hüüdma', 'abielu', 'kulu', 'nõrk', 'murdma', 'kursus',
                 'esindama', 'ülejäänud', 'võime', 'peatuma', 'registreerima', 'säilitama', 'nimel', 'väljas',
                 'teadlane', 'olemus', 'rajama', 'lõikama', 'vaikima', 'näidend', 'siga', 'rikkuma', 'maht', 'kala',
                 'ebavõrdsus', 'tootmine', 'raskus', 'mägi', 'lennuk', 'laupäev', 'õpik', 'hooaeg', 'harjuma',
                 'üleminek', 'täielikult', 'teisiti', 'ääres', 'etapp', 'nentima', 'ükskõik', 'suunas', 'vastupidi',
                 'läbima', 'piisama', 'miljard', 'kogus', 'eelarve', 'õnnelik', 'külaline', 'värav', 'pudel',
                 'karakteristik', 'meedia', 'otsekui', 'korraldus', 'sekund', 'ärkama', 'vaim', 'ring', 'hammas',
                 'küllalt', 'saal', 'nõustuma', 'elektrooniline', 'aktiivne', 'õieti', 'tasku', 'edu', 'poliitik',
                 'mitmesugune', 'kolleeg', 'karistus', 'arendamine', 'kõndima', 'kohtama', 'traditsiooniline', 'lumi',
                 'lind', 'sakslane', 'ajakiri', 'mujal', 'ametlik', 'suits', 'niimoodi', 'rahu', 'tõde', 'koosseis',
                 'puudus', 'tutvustama', 'sisemine', 'otseselt', 'ajakirjandus', 'maks', 'ah', 'imestama', 'iseloom',
                 'homme', 'siiani', 'tehnoloogia', 'nali', 'pikkus', 'energia', 'kaunis', 'mistõttu', 'kätte', 'kumbki',
                 'häda', 'toode', 'seltskond', 'värske', 'sinine', 'tudeng', 'härra', 'kuivõrd', 'võrdne', 'teaduslik',
                 'keset', 'kava', 'töökoht', 'mälu', 'tõdema', 'termin', 'sätestama', 'päästma', 'nimekiri', 'masin',
                 'kaaluma', 'andmine', 'öösel', 'edukas', 'käik', 'esinemine', 'tulenema', 'tajuma', 'käituma', 'käest',
                 'vili', 'võitlema', 'võrdlus', 'lõpetamine', 'külge', 'kontsert', 'kliiniline', 'nutma', 'kerkima',
                 'taoline', 'luuletus', 'tõsiselt', 'vahtima', 'olemasolev', 'täpne', 'laut', 'kippuma', 'õlu', 'usk',
                 'lahendamine', 'reede', 'kah', 'õu', 'reaalne', 'ajalooline', 'juur', 'tulevane', 'temperatuur',
                 'kõht', 'kuningas', 'eemale', 'lähenemine', 'välistama', 'kordama', 'eelnev', 'pistma', 'pakkumine',
                 'valmima', 'pühapäev', 'õnnetus', 'kirjeldus', 'keskenduma', 'eriala', 'spetsialist', 'tulu', 'rada',
                 'meenuma', 'aste', 'tera', 'pealinn', 'uudis', 'paks', 'edasine', 'tellima', 'lisanduma', 'alkohol',
                 'omavaheline', 'tahtlus', 'iseseisev', 'tähele', 'pidev', 'lihtsam', 'vaikne', 'jälg', 'eestikeelne',
                 'arendama', 'teistsugune', 'ohtlik', 'korraldamine', 'hull', 'kriteerium', 'ronima', 'võitlus',
                 'keskel', 'tekkimine', 'vaikselt', 'tume', 'tehniline', 'raamatukogu', 'hüppama', 'roheline', 'mullu',
                 'treener', 'takistama', 'investeering', 'oh', 'muutmine', 'omaette', 'tädi', 'teel', 'missugune',
                 'asutus', 'üritus', 'sõnum', 'hotell', 'karjuma', 'tarkvara', 'kass', 'politseinik', 'liider', 'toon',
                 'proteiin', 'operatsioon', 'muudatus', 'ükskord', 'asetama', 'mass', 'õiguslik', 'põhinema', 'üksus',
                 'leidmine', 'looming', 'kuskil', 'kogunema', 'sagedamini', 'minevik', 'hõlmama', 'sõit', 'tulenev',
                 'traditsioon', 'kohv', 'esmaspäev', 'rakk', 'klaas', 'korraks', 'komi', 'vein', 'laen',
                 'ettevaatusprintsiip', 'soomlane', 'pärinema', 'oletama', 'saade', 'kuritegu', 'pärima', 'harva',
                 'arusaam', 'vaene', 'relv', 'neiu', 'eraldama', 'tundmatu', 'liikmesriik', 'ühiskondlik', 'levik',
                 'kasulik', 'sügav', 'läbirääkimine', 'liha', 'vastuolu', 'rong', 'siinkohal', 'suhtuma', 'minister',
                 'andmebaas', 'mõtlemine', 'kuri', 'olemine', 'tootma', 'kaugus', 'süüdistama', 'kulutama', 'kaasaegne',
                 'põlv', 'süüdistatav', 'kaugel', 'tuletama', 'lõhn', 'laiem', 'enamus', 'vaikus', 'hool', 'siinne',
                 'maantee', 'vähenemine', 'korrus', 'aeg-ajalt', 'kummaline', 'kena', 'kõvasti', 'tugevam', 'rahvus',
                 'esitamine', 'välismaa', 'ehitus', 'side', 'tõlge', 'tahtmine', 'koostamine', 'vahelt', 'kuum',
                 'esiteks', 'raadio', 'põhiline', 'sisuliselt', 'peatükk', 'asendama', 'omane', 'kott', 'kuulus',
                 'vihm', 'hiljuti', 'teostama', 'trepp', 'põgenema', 'lähedane', 'tore', 'jutustama', 'kohtunik',
                 'teatav', 'pehme', 'mahtuma', 'kujundama', 'reis', 'arvutama', 'aed', 'eksima', 'eeskuju', 'veenduma',
                 'sadam', 'vanamees', 'eelnõu', 'avanema', 'üheksa', 'sealhulgas', 'saavutamine', 'määratlema', 'muide',
                 'teke', 'säilima', 'keelduma', 'ressurss', 'päritolu', 'tool', 'lähenema', 'linnapea', 'huul',
                 'tänama', 'teadus', 'seevastu', 'ohver', 'naaber', 'auk', 'ühtne', 'eksisteerima', 'organ',
                 'praktiline', 'järsku', 'mõistus', 'laiali', 'põhiliselt', 'järjekord', 'tark', 'reklaam', 'luba',
                 'metoodika', 'kitsas', 'seade', 'hilisem', 'esialgne', 'kõva', 'vaev', 'taotlus', 'muutumine',
                 'kujunemine', 'kaasnema', 'häirima', 'avalikkus', 'raskem', 'taotlema', 'nõu', 'test', 'tipp',
                 'piisav', 'ootamatult', 'peagi', 'katus', 'hoog', 'süüdi', 'keskkõrge', 'järelikult', 'ese', 'aus',
                 'vaimne', 'kaasas', 'põhiseadus', 'kakskümmend', 'aktiivsus', 'õppejõud', 'tuginema', 'pimedus',
                 'klassikaline', 'kanal', 'väsima', 'suurenemine', 'organism', 'kokkuleppemenetlus', 'iseloomulik',
                 'osaliselt', 'uhke', 'serv', 'rikkumine', 'intervjuu', 'ainuke', 'tunnustama', 'konflikt',
                 'arvatavasti', 'toetuma', 'piirduma', 'pinge', 'kommenteerima', 'tehing', 'mõningas', 'plats',
                 'niivõrd', 'kodumaa', 'säärane', 'pesema', 'aadress', 'põld', 'kollane', 'eespool', 'lõige', 'lõplik',
                 'kiskuma', 'leib', 'sõdur', 'kiiremini', 'kaugele', 'kandidaat', 'kunagine', 'eilne', 'kari', 'võrk',
                 'kõrgus', 'kategooria', 'pall', 'käes', 'kesklinn', 'küllaltki', 'muretsema', 'demokraatia',
                 'noogutama', 'kodune', 'standard', 'plaat', 'võimeline', 'äärmiselt', 'vastuvõtja', 'register',
                 'määrus', 'kapital', 'parajasti', 'töötav', 'raames', 'pisike', 'viin', 'statistiliselt', 'koostis',
                 'järgima', 'mõnevõrra', 'väljaspool', 'paigutama', 'kolmandik', 'asukoht', 'vaenlane', 'suhtlema',
                 'peegel', 'loll', 'kestus', 'korjama', 'iseenesest', 'õpetamine', 'kirjutamine', 'jalutama',
                 'sooritama', 'kogema', 'õppija', 'vang', 'aju', 'situatsioon', 'ajastu', 'saadik', 'liiv', 'sugulane',
                 'parlament', 'lill', 'ime', 'kaotus', 'täiendama', 'onu', 'teave', 'sild', 'perearst', 'peitma',
                 'kurb', 'indiviid', 'vastutama', 'teoreetiline', 'külastama', 'kohvik', 'efektiivsus',
                 'põhimõtteliselt', 'efektiivne', 'veetma', 'uurimistöö', 'kättesaadav', 'ameeriklane', 'vastuvõtt',
                 'sosistama', 'ase', 'terav', 'kriminaalmenetlus', 'tegija', 'rikas', 'protsessor', 'vaade', 'saladus',
                 'kinkima', 'paljas', 'pilet', 'nõudmine', 'koondis', 'faktor', 'üllatus', 'muigama', 'laad',
                 'seisnema', 'vaidlema', 'vabastama', 'tõenäosus', 'proov', 'fikseerima', 'tõlkima', 'rahvahääletus',
                 'koosolek', 'ähvardama', 'tegelikkus', 'rahulik', 'lehekülg', 'keskkool', 'muna', 'pikaajaline',
                 'kehtiv', 'tööleping', 'käive', 'aimama', 'kaaslane', 'lähemalt', 'kindlalt', 'kergelt', 'mari',
                 'menetlus', 'kahtlemata', 'süüdistus', 'kontsentratsioon', 'järv', 'viies', 'usaldama', 'rahuldama',
                 'rünnak', 'nautima', 'aastakümme', 'kaupa', 'lahkumine', 'hoiak', 'ehitamine', 'vahest', 'pealkiri',
                 'paha', 'lääs', 'kasum', 'heli', 'proua', 'märksa', 'mängija', 'korralikult', 'võti', 'vaatlus',
                 'väljuma', 'väline', 'skaala', 'näpp', 'kontakt', 'kahtlema', 'esmalt', 'armas', 'võitja', 'vaimulik',
                 'rahulikult', 'lõuna', 'vahetu', 'kuiv', 'elanikkond', 'ümbrus', 'erand', 'kommunikatsioon', 'tormama',
                 'nüüdne', 'kindlustama', 'au', 'võimas', 'skeem', 'silp', 'ootus', 'käskima', 'heaks', 'katsuma',
                 'tõend', 'tungima', 'tubli', 'tihe', 'teisalt', 'tüvi', 'tütarlaps', 'nimetus', 'vältel', 'tasakaal',
                 'täheldama', 'viitsima', 'meister', 'kulgema', 'segadus', 'jagu', 'maitse', 'tagamine', 'seostama',
                 'pilv', 'tootja', 'jott', 'võte', 'ekraan', 'talupoeg', 'sünnipäev', 'stiil', 'enam-vähem', 'vabalt',
                 'lugemine', 'kulutus', 'raputama', 'olek', 'neljapäev', 'mootor', 'las', 'hingama', 'rakendus',
                 'kallas', 'täiendav', 'mõõtmine', 'õigustama', 'vägi', 'arutelu', 'täpsemalt', 'subjekt', 'verb',
                 'minek', 'konkurss', 'tehnika', 'konkurents', 'kiht', 'avalduma', 'varblane', 'liigutama', 'baas',
                 'torkama', 'partner', 'ohkama', 'muuseum', 'kultuuriline', 'toimetama', 'kallim', 'soodustama',
                 'paiknema', 'kingitus', 'saun', 'infosüsteem', 'tulev', 'korduvalt', 'kaal', 'praktiliselt', 'äsja',
                 'staatus', 'lähemale', 'unistus', 'trükis', 'sõltuvalt', 'valetama', 'soovitus', 'olenema',
                 'eksperiment', 'direktiiv', 'sealne', 'meeldiv', 'kolima', 'agent', 'otsas', 'reaktsioon', 'väljaanne',
                 'hirmus', 'mõnus', 'muster', 'aeglaselt', 'vanaisa', 'sadama', 'osaline', 'lapsepõlv', 'väljak',
                 'kirjakeel', 'täiskasvanu', 'igati', 'igapäevane', 'hukkuma', 'reageerima', 'ministeerium', 'lubadus',
                 'vähendamine', 'kauge', 'valdavalt', 'sõiduk', 'rand', 'küsitlus', 'eelis', 'ühing', 'liin', 'rohi',
                 'hele', 'viirus', 'tere', 'pressiesindaja', 'kergem', 'konverents', 'sünd', 'mõis', 'hulgast',
                 'voolama', 'vangla', 'tantsima', 'regulatsioon', 'kohati', 'versioon', 'jaotus', 'ilme', 'krooniline',
                 'väljend', 'kahjustama', 'püks', 'katkestama', 'viimaks', 'parandamine', 'varastama', 'reguleerima',
                 'näol', 'mõistmine', 'karistama', 'korrelatsioon', 'juurest', 'tõlgendus', 'puhkama', 'meede',
                 'institutsioon', 'ennustama', 'sööt', 'millegipärast', 'rippuma', 'ettekanne', 'väärima', 'teisipäev',
                 'territoorium', 'sari', 'loogiline', 'vastaja', 'mõistlik', 'vasak', 'korraldaja', 'tulenevalt',
                 'kiirustama', 'täpsustama', 'eeskätt', 'vahetult', 'ohvitser', 'karm', 'fond', 'kogudus', 'välimus',
                 'keskne', 'õpetus', 'ettevalmistus', 'saba', 'ratas', 'tutvuma', 'kolmapäev', 'äri', 'äratama',
                 'osalemine', 'märg', 'halvasti', 'doktor', 'võlg', 'nagunii', 'kana', 'sümbol', 'odavam',
                 'järjekordne', 'pühkima', 'lähedus', 'naer', 'raudtee', 'kirjeldamine', 'organisatsioonikultuur',
                 'kihutama', 'suhtlemine', 'purjus', 'liigutus', 'kuld', 'kartul', 'juhtkond', 'emotsionaalne',
                 'asutama', 'valama', 'teenistus', 'suhteline', 'efekt', 'daam', 'väljenduma', 'edukalt', 'põhinev',
                 'ligikaudu', 'muudkui', 'subjektiivne', 'ründama', 'kaudne', 'tõug', 'tollal', 'püstitama', 'piirang',
                 'langus', 'vabanema', 'pihta', 'muuseas', 'kindral', 'vestlus', 'restoran', 'olu', 'looduslik',
                 'koolitus', 'kavandama', 'sõjavägi', 'odav', 'esmakordselt', 'perenaine', 'ootamatu', 'kriitiline',
                 'unenägu', 'täitsa', 'teadvus', 'reaalsus', 'juhuslik', 'hävitama', 'grammatika', 'varustama',
                 'valitsev', 'tonn', 'luule', 'ettekujutus', 'pihk', 'põllumajandus', 'kauplus', 'pisar', 'langetama',
                 'lahutama', 'hullem', 'vahendus', 'suurepärane', 'magneesium', 'üldjuht', 'tahes', 'peatama',
                 'paranema', 'naeratus', 'poolteist', 'kurtma', 'ulatama', 'lahtine', 'ühinema', 'viimati', 'tarbija',
                 'morfoloogiline', 'järeldama', 'äge', 'lamama', 'ettevõtja', 'festival', 'peksma', 'luu', 'koridor',
                 'karjäär', 'identiteet', 'kraad', 'pühendama', 'pikalt', 'osaleja', 'matma', 'kurk', 'soodne',
                 'seletus', 'eelnevalt', 'paras', 'mark', 'keemiline', 'kasvõi', 'kapten', 'ravima', 'park', 'lühem',
                 'haigekassa', 'atmosfäär', 'tohutu', 'defineerima', 'allkiri', 'asutamine', 'puhuma', 'kasvatamine',
                 'jaotama', 'äärde', 'surve', 'signaal', 'mingisugune', 'laine', 'edastama', 'ajavahemik', 'üpris',
                 'viha', 'teiseks', 'abielluma', 'säilitamine', 'strateegia', 'kustutama', 'rõõmustama', 'rõõmus',
                 'objektiivne', 'kuulaja', 'esinev', 'tõmbuma', 'vabandama', 'sõbranna', 'moodne', 'vait', 'lähtuvalt',
                 'armee', 'taluma', 'taastama', 'lavastaja', 'häire', 'matemaatika', 'kollektiivne', 'selgus',
                 'kõrgharidus', 'ümbritsev', 'ilu', 'eemal', 'sarnanema', 'lõplikult', 'liikuv', 'esmane', 'aastane',
                 'õnnetu', 'tulek', 'kontseptsioon', 'elus', 'kohustama', 'kaebama', 'teadlik', 'korrigeerima',
                 'akadeemiline', 'tava', 'parameeter', 'naasma', 'issand', 'väljatöötamine', 'tööjõud', 'osatähtsus',
                 'algatama', 'uuritav', 'tüüpiline', 'lülitama', 'igav', 'tüli', 'samamoodi', 'nädalavahetus',
                 'kangelane', 'juut', 'sarnasus', 'järgnevalt', 'individuaalne', 'auhind', 'püsiv', 'haud', 'vahetus',
                 'vahemik', 'maine', 'kujundamine', 'tagasiside', 'puhkus', 'peadirektor', 'mõõde', 'hoiatama', 'pink',
                 'kohustuslik', 'kleit', 'ärimees', 'ruttu', 'puudutav', 'ookean', 'kapp', 'arhiiv', 'vaidlus', 'tiib',
                 'nähtavasti', 'välisminister', 'lipp', 'põsk', 'konkurent', 'istung', 'lagi', 'tähtaeg',
                 'suurendamine', 'stress', 'kriitika', 'kaugemale', 'töötlemine', 'sagedus', 'kõikjal', 'sirutama',
                 'päriselt', 'paratamatult', 'avamine', 'veerand', 'vastupidine', 'vahekord', 'sedavõrd', 'rahaline',
                 'meelitama', 'kahjustus', 'vahendama', 'põnev', 'peatreener', 'kallal', 'toru', 'sõltumatu', 'pull',
                 'kahtlustama', 'tänavune', 'euro', 'sekretär', 'gümnaasium', 'kino', 'kõrgenema', 'kauem', 'tookord',
                 'paarkümmend', 'jagunema', 'tuvastama', 'juhtiv', 'niigi', 'sportlane', 'liigne', 'jook', 'teostamine',
                 'muinasjutt', 'kannatanu', 'juhatama', 'esitus', 'mõttetu', 'ülejäänu', 'libisema', 'funktsionaalne',
                 'tollane', 'läbiviimine', 'metsavend', 'käsitlemine', 'eemaldama', 'ujuma', 'usaldus', 'turist',
                 'pikkune', 'loeng', 'vältimine', 'riigieelarve', 'käsikiri', 'klooster', 'argument', 'ajutine',
                 'kutse', 'igavene', 'ühinemine', 'lähem', 'hiir', 'finaal', 'elamine', 'vastavus', 'tehas',
                 'sissejuhatus', 'rumal', 'rebima', 'ostja', 'maailmasõda', 'löök', 'valus', 'milleks', 'mehhanism',
                 'kurss', 'iial', 'vanasõna', 'kiirem', 'kergesti', 'toodang', 'hoolitsema', 'ausalt', 'tuju',
                 'psühholoogiline', 'harjutama', 'elekter', 'ühesugune', 'tänaseks', 'arhitektuur', 'tendents', 'rubla',
                 'sugu', 'kõrb', 'viide', 'valija', 'valesti', 'tagasihoidlik', 'sõltuvus', 'pruun', 'koormus',
                 'takistus', 'sarnaselt', 'king', 'kabinet', 'jää', 'juhuslikult', 'värss', 'nõusolek', 'diagnoos',
                 'konventsioon', 'kaasnev', 'valim', 'unistama', 'spetsiaalne', 'preemia', 'kehv', 'demokraatlik',
                 'muutuja', 'võtmine', 'kommentaar', 'puhkema', 'kriitik', 'hoolima', 'drillprogramm', 'vaat',
                 'otstarbekas', 'tõeliselt', 'tekk', 'sisalduma', 'sisaldav', 'palve', 'mikrovõrse', 'laskuma', 'jahe',
                 'ekspert', 'seostuma', 'pastor', 'jama', 'stabiilne', 'piibel', 'vajutama', 'kristlik', 'kogumine',
                 'arutlema', 'sotsiaaltöö', 'põhjalikult', 'seltsimees', 'protokoll', 'petma', 'laiendama', 'kolhoos',
                 'kirjutis', 'valmistamine', 'rajamine', 'müüja', 'lämmastik', 'looja', 'juhus', 'hüpotees', 'liituma',
                 'kole', 'põllumees', 'kalduma', 'kolmkümmend', 'aparaat', 'draama', 'saatja', 'materiaalne',
                 'lastekodu', 'joonistama', 'hankima', 'väärt', 'protseduur', 'pension', 'patt', 'nähtav', 'laulja',
                 'iseseisvus', 'õigesti', 'vererõhk', 'rahulolu', 'pomisema', 'moodustuma', 'spetsiifiline', 'laenama',
                 'kaasama', 'torn', 'reform', 'põhjalik', 'omistama', 'linnaosa', 'kõrvalt', 'tervitama', 'suurune',
                 'tunnistus', 'täpsus', 'niikuinii', 'lõhkuma', 'koondama', 'ihu', 'faas', 'sisuline', 'nupp', 'moodi',
                 'kooskõla', 'õli', 'tavapärane', 'vanker', 'tõstmine', 'tants', 'liitumine', 'tarvitama', 'planeerima',
                 'meeleolu', 'tugi', 'tarbimine', 'kehtestamine', 'isand', 'ametlikult', 'tõrjuma', 'meditsiin',
                 'inimlik', 'öine', 'sisenema', 'postmodernism', 'peituma', 'paus', 'nuga', 'naisterahvas', 'jõudmine',
                 'aruanne', 'ida', 'eel', 'valem', 'tunnetama', 'selgitus', 'osalus', 'kontor', 'kombinatsioon', 'lend',
                 'laienema', 'kargama', 'seonduv', 'reisija', 'potentsiaalne', 'panus', 'särk', 'gaas', 'takso',
                 'suudlema', 'seisev', 'eluaasta', 'kusagilt', 'haigestumine', 'dünaamiline', 'dialoog', 'voor',
                 'surnu', 'lahing', 'kaamera', 'hääletama', 'hilja', 'õppekava', 'kõigest', 'otsimine', 'maksimaalne',
                 'ennekõike', 'venekeelne', 'peegeldama', 'kumb', 'õun', 'vanalinn', 'tapmine', 'sulg', 'laekuma',
                 'tegutsemine', 'pugema', 'diagnoosima', 'autojuht', 'pälvima', 'äriühing', 'täpsem', 'osapool',
                 'niipalju', 'jällegi', 'töötlema', 'süli', 'põhjendus', 'maal', 'liialt', 'sport', 'veider', 'noorus',
                 'lasteaed', 'pass', 'isiksus', 'märkimisväärne', 'ettevõtmine', 'eripära', 'seminar', 'naljakas',
                 'kavatsus', 'turniir', 'korpus', 'jaa', 'isiklikult', 'populaarne', 'luuletaja', 'kehaline', 'raud',
                 'kongress', 'keerukas', 'vigastama', 'treening', 'organiseerima', 'kasvav', 'ametikoht', 'väitekiri',
                 'silmitsema', 'pakk', 'motiiv', 'kroonika', 'remont', 'prantslane', 'kuues', 'kahetsema', 'arusaamine',
                 'valdama', 'statistiline', 'rahvastik', 'määratlemine', 'emotsioon', 'tööline', 'süütama', 'saatkond',
                 'pingutama', 'asemele', 'töötu', 'saavutus', 'lammas', 'kaugusel', 'värisema', 'tekitaja',
                 'kurjategija', 'eeltoodu', 'üksinda', 'tõlgendama', 'loss', 'kümmekond', 'julgeolek', 'ilmne',
                 'pädevus', 'prognoos', 'haridusministeerium', 'vastanu', 'tromb', 'suuresti', 'märgatavalt', 'raam',
                 'kallale', 'investeerima', 'harima', 'domineerima', 'kaebus', 'jagamine', 'moment', 'häbi',
                 'võrreldav', 'toimetus', 'optimaalne', 'omaenese', 'kahtlane', 'indeks', 'esikoht', 'alumine',
                 'salvestama', 'üleval', 'sektor', 'alistama', 'kriis', 'ettevaatlikult', 'alluma', 'pluss', 'tööstus',
                 'suitsetama', 'omamoodi', 'leid', 'kajastama', 'põletama', 'lõik', 'trükkima', 'rahule', 'erastamine',
                 'vihkama', 'ulatuslik', 'televisioon', 'lahus', 'koosnev', 'aeglane', 'suunduma', 'statistika',
                 'kõrgeim', 'kaitsevägi', 'ülestunnistus', 'vigastus', 'siht', 'nelikümmend', 'kasvatus', 'kaasaeg',
                 'halvem', 'vähim', 'võistlema', 'vallandamine', 'heaolu', 'sümptom', 'oks', 'valmistuma', 'lihas',
                 'kange', 'lõbus', 'kood', 'emakeel', 'ümbritsema', 'säte', 'hinne', 'eksam', 'eitama', 'tulumaks',
                 'toppima', 'rasv', 'perspektiiv', 'maastik', 'kvartal', 'kohaldamine', 'professionaalne', 'kommunist',
                 'lõug', 'katseaasta', 'bioloogiline', 'ainuüksi', 'ööpäev', 'õigemini', 'sekka', 'rütm', 'peen',
                 'otsustav', 'kuivaine', 'geneetiline', 'geen', 'vestlema', 'pensionär', 'pagan', 'müür', 'minimaalne',
                 'kandja', 'laienemine', 'järelevalve', 'annus', 'ülemus', 'äär', 'vastastikune', 'tramm', 'tihedalt',
                 'plaanima', 'murre', 'magus', 'loov', 'sügavalt', 'sealjuures', 'orgaaniline', 'tiitel', 'saatel',
                 'otsustamine', 'kujutlema', 'kadumine', 'haridustase', 'märkus', 'laager', 'kõikvõimalik', 'kirjalik',
                 'selgitamine', 'nõrgem', 'kõlbama', 'tekkiv', 'ostmine', 'käivitama', 'korduv', 'asend', 'üllatama',
                 'realiseerima', 'muuhulgas', 'mimikri', 'pakutav', 'särama', 'seast', 'prill', 'kõrgkool', 'kant',
                 'definitsioon', 'tervishoid', 'sünnitama', 'plahvatus', 'lepe', 'jaksama', 'õigusvõime', 'saabumine',
                 'moodustamine', 'ebameeldiv', 'ülemine', 'tühine', 'tegutsev', 'sügavus', 'sügavam', 'muusikaline',
                 'kude', 'kooslus', 'inimkond', 'börs', 'jääv', 'taastamine', 'paragrahv', 'kohtuotsus', 'etniline',
                 'ebakindlus', 'dimensioon', 'välismaalane', 'vägivald', 'plika', 'kulg', 'kiirabi', 'täiskasvanud',
                 'sõlmimine', 'infotehnoloogia', 'tõbi', 'tugevus', 'toimimine', 'telekas', 'nojah', 'fraktsioon',
                 'kaupmees', 'jube', 'infektsioon', 'katsetama', 'väidetavalt', 'süntees', 'server', 'kuivama',
                 'kampaania', 'toiduaine', 'lühidalt', 'tulistama', 'pankrot', 'null', 'niiviisi', 'lahend',
                 'intensiivsus', 'baar', 'toiming', 'teekond', 'süvenema', 'nooruk', 'laip', 'armuma', 'parasjagu',
                 'maalima', 'lapsevanem', 'rikkus', 'proteiinisisaldus', 'ülem', 'vast', 'ettenähtud', 'andeks', 'õis',
                 'turvalisus', 'röövima', 'oder', 'mõistagi', 'meistrivõistlus', 'analüüsimine', 'seest', 'prokuratuur',
                 'planeet', 'loetelu', 'keerulisem', 'vastuvõtmine', 'vabatahtlik', 'torm', 'paat', 'neelama', 'kilo',
                 'kast', 'impeerium', 'algoritm', 'mõistetav', 'kuldne', 'kujutlus', 'uuem', 'usutav', 'kukal',
                 'pöördumine', 'post', 'ettevalmistamine', 'loogika', 'kohtulik', 'kannatus', 'ilmutama', 'preparaat',
                 'määratlus', 'kuupäev', 'enim', 'eelnema', 'absoluutne', 'õigusakt', 'segu', 'kops', 'kontrollimine',
                 'kliima', 'kaitsmine', 'jätkuvalt', 'jalgpall', 'bänd', 'väljakutse', 'sünnitus', 'seeläbi',
                 'planeerimine', 'närv', 'lagunema', 'järsk', 'haruldane', 'arusaamatu', 'üleeile', 'viiv', 'trahv',
                 'pingutus', 'kaas', 'ülikond', 'modell', 'arstiabi', 'õigupoolest', 'visiit', 'valgustama', 'sihuke',
                 'olümpia', 'vats', 'taanduma', 'segane', 'möödas', 'linnavolikogu', 'risti', 'mõjul', 'aktsepteerima',
                 'aim', 'ahi', 'stsenaarium', 'sealsamas', 'koor', 'empiiriline', 'sihtasutus', 'puudu',
                 'konsistoorium', 'eetiline', 'udu', 'sirge', 'piires', 'nimisõna', 'määrav', 'muutuv', 'medal',
                 'detail', 'tugevasti', 'ilmumine', 'varieeruma', 'omandamine', 'vaadeldav', 'tehtav', 'sool',
                 'kuulsus', 'kohutav', 'jaam', 'vastik', 'põõsas', 'mamma', 'majanduskasv', 'loodetavasti', 'koristama',
                 'automaatselt', 'stseen', 'sisalduv', 'opositsioon', 'ettevaatlik', 'puhk', 'varane', 'targem',
                 'sulama', 'lohutama', 'keetma', 'katki', 'jälgimine', 'hunt', 'elukoht', 'väetamine', 'möönma',
                 'kahekesi', 'seeme', 'riiul', 'kaugelt', 'hein', 'söök', 'absoluutselt', 'sekkuma', 'segi', 'oi',
                 'küljes', 'sigaret', 'nälg', 'kustuma', 'kindlus', 'häbenema', 'ülimalt', 'testament', 'sent',
                 'kaitsja', 'eksport', 'algatus', 'vihje', 'regilaul', 'moodul', 'depressioon', 'ansambel',
                 'viiskümmend', 'valdav', 'tempo', 'somaatiline', 'narkootikum', 'mõõt', 'abstraktne', 'verine',
                 'arhitekt', 'töötamine', 'rekord', 'lebama', 'kõiv', 'kogukond', 'ideoloogiline', 'eelistus',
                 'diagnoosimine', 'advokaat', 'veenma', 'veendumus', 'tõsiasi', 'mobiiltelefon', 'lukk', 'kirjeldav',
                 'juhendaja', 'harilik', 'e-õpe', 'ehitis', 'arvestus', 'ütlus', 'tarkus', 'soojus', 'pooleli',
                 'koputama', 'erialane', 'otstarve', 'märgend', 'mugav', 'lisamine', 'lett', 'kütus', 'fänn',
                 'maksmine', 'kriminaalasi', 'rahvuslus', 'söötmine', 'rändama', 'paiku', 'nõunik', 'toetamine', 'habe',
                 'diskussioon', 'arvutus', 'aktiivselt', 'testimine', 'selgesti', 'rusikas', 'liitma', 'arutamine',
                 'puit', 'pigistama', 'lõputu', 'tunnustus', 'käibemaks', 'vedelema', 'tugevalt', 'strateegiline',
                 'kelder', 'isoleerima', 'algselt', 'vaevama', 'kandev', 'järgmiselt', 'õpe', 'tingimata', 'tarve',
                 'siinsamas', 'samaaegselt', 'regioon', 'range', 'sõbralik', 'rahakott', 'leiduv', 'kuul', 'korv',
                 'kandideerima', 'hüvitis', 'kääne', 'üksikisik', 'õhuke', 'mõõdukas', 'toimetulek', 'revolutsioon',
                 'hõikama', 'hoiduma', 'veis', 'varas', 'tõukama', 'traktor', 'seepeale', 'nägemus', 'hoidmine',
                 'esinemissagedus', 'kujund', 'õrn', 'värvima', 'puhastama', 'loovus', 'lennujaam', 'labor', 'küünal',
                 'koopia', 'kevadine', 'jurist', 'jooks', 'iseloomustav', 'igatsema', 'ideoloogia', 'üksainus', 'välde',
                 'stabiilsus', 'staadion', 'kõrvuti', 'iste', 'muusik', 'maksumus', 'akt', 'virutama', 'sõnastama',
                 'silt', 'salajane', 'piiskop', 'pidamine', 'laht', 'helilooja', 'valvama', 'tööturg', 'sättima',
                 'vähegi', 'prokurör', 'lamp', 'arusaadav', 'välisministeerium', 'varajane', 'paranemine', 'olend',
                 'niiske', 'liiklus', 'arm', 'ankeet', 'venima', 'suhkur', 'olematu', 'kutt', 'formaalne', 'alustamine',
                 'teene', 'rootslane', 'oletus', 'kõikuma', 'jutustus', 'vormistama', 'valk', 'postmodernistlik',
                 'värk', 'teatavasti', 'pikemalt', 'kirg', 'haigestuma', 'esitatav', 'arvutamine', 'võrse',
                 'võrdlemine', 'riskima', 'prognoosima', 'maksuamet', 'terviklik', 'teinekord', 'saabas', 'toimiv',
                 'teadmata', 'sõnaraamat', 'luterlik', 'automaat', 'õppetöö', 'söötma', 'liiter', 'katkema',
                 'iseärasus', 'tööpäev', 'kommunistlik', 'infrastruktuur', 'väli', 'rahvaalgatus', 'järsult', 'hektar',
                 'arvel', 'ajaline', 'viimne', 'vallandama', 'valitseja', 'tagantjärele', 'registreerimine', 'märksõna',
                 'maitsma', 'intellektuaalne', 'hämar', 'andmekogu', 'ümberringi', 'realiseerimine', 'raiuma', 'niipea',
                 'müüt', 'loobumine', 'tolm', 'tekitamine', 'süntaktiline', 'pruut', 'maapind', 'kirjanduslik', 'kild',
                 'asjatundja', 'alaealine', 'lina', 'keiser', 'siiamaani', 'kogemata', 'julgus', 'tõotama',
                 'tõenäoline', 'turvaline', 'sulane', 'pikali', 'järglane', 'ilusam', 'diivan', 'ühend', 'poolaeg',
                 'kummarduma', 'austama', 'ajaloolane', 'tass', 'soo', 'saadav', 'küsimustik', 'kõver', 'kogum',
                 'kaotamine', 'initsiatiiv', 'imetlema', 'aktuaalne', 'väärtuslik', 'võrdselt', 'tsükkel',
                 'suitsetamine', 'siirduma', 'religioon', 'asetäitja', 'allusioon', 'varandus', 'teistmoodi', 'rool',
                 'psühholoog', 'kaltsium', 'ametiühing', 'uriin', 'kohapeal', 'investor', 'büroo', 'avalikult',
                 'sallima', 'maas', 'kahanema', 'hiilima', 'õpitarkvara', 'võlausaldaja', 'teadvustama', 'rahastamine',
                 'loetlema', 'laduma', 'kirjastus', 'tulekahju', 'globaalne', 'võrdlemisi', 'süütu', 'pidurdama',
                 'koefitsient', 'hüvitamine', 'semantiline', 'robot', 'piinlik', 'napp', 'kõneleja', 'kohver',
                 'hoopiski', 'udar', 'tellimus', 'puue', 'osalt', 'jalgratas', 'elluviimine', 'ahel', 'õiglane',
                 'võpatama', 'kättesaadavus', 'krunt', 'eurooplane', 'eristamine', 'allapoole', 'väljund', 'võimsus',
                 'vihane', 'seitsmes', 'saagikus', 'kritiseerima', 'haav', 'digitaalne', 'avastamine', 'aktsiaselts',
                 'õunapuu', 'õigeusk', 'uudne', 'tõsisem', 'sõjaline', 'suremus', 'farm', 'pööre', 'moraalne',
                 'keskpaik', 'ideaal', 'algav', 'vajalikkus', 'vaagen', 'tundlik', 'staadium', 'juhtunu', 'uhkus',
                 'ruutmeeter', 'mõõk', 'elukvaliteet', 'edetabel', 'tasa', 'mantel', 'koalitsioon', 'harjumus',
                 'biograafia', 'teavitama', 'sündroom', 'ruttama', 'põrgu', 'pulm', 'pettuma', 'otsing', 'osutamine',
                 'maailmameister', 'vanasti', 'toitma', 'taguma', 'riskitegur', 'rasvhape', 'pärastlõuna', 'kallama',
                 'tegelev', 'rektor', 'pedagoogiline', 'müts', 'kaugeltki', 'eelnimetatu', 'abiline', 'ärevus',
                 'suvine', 'leek', 'kardin', 'fantaasia', 'riputama', 'otsustus', 'määrima', 'lähim', 'kuskilt',
                 'ettevõtlus', 'demonstreerima', 'söandama', 'purustama', 'pesa', 'menüü', 'kvalifikatsioon',
                 'informeerima', 'hõivama', 'hoolikalt', 'arust', 'armuke', 'andekas', 'põdema', 'peategelane',
                 'meditsiiniline', 'köide', 'arvutivõrk', 'õigem', 'tunnistaja', 'treenima', 'ehtne',
                 'sotsiaalministeerium', 'seisus', 'rasedus', 'kõrvaldama', 'elusolend', 'üleni', 'volitus',
                 'televiisor', 'märgatav', 'antikeha', 'tänapäevane', 'režissöör', 'poisike', 'olulisus', 'nõudlus',
                 'mõnu', 'majanduslikult', 'kaubamaja', 'kattuma', 'hommikune', 'väärtustama', 'vanduma', 'tsiteerima',
                 'sokk', 'rüüpama', 'piiluma', 'kütma', 'vool', 'valutama', 'vallavanem', 'usaldusväärne', 'tuline',
                 'tasapisi', 'noot', 'mullune', 'inimõigus', 'harilikult', 'uuendus', 'pidulik', 'kvaliteetne',
                 'arstiteaduskond', 'suvaline', 'riigikohus', 'söömine', 'sõnastik', 'reetma', 'lätlane', 'lagunemine',
                 'koonduma', 'kenasti', 'õhtune', 'toimetaja', 'silo', 'keerutama', 'arengukava', 'alternatiiv',
                 'vastsündinu', 'preester', 'kombineerima', 'kitsendus', 'hüpe', 'vilets', 'tagumine', 'seaduslik',
                 'kehitama', 'tartlane', 'silitama', 'püss', 'homne', 'eesots', 'ühesõnaga', 'prioriteet', 'personal',
                 'kõrgelt', 'kuusk', 'valmimine', 'tõlgendamine', 'sõprus', 'allpool', 'abilinnapea', 'vannituba',
                 'tõendama', 'pelgama', 'paralleelselt', 'ohustama', 'munk', 'läbiviidud', 'kähku', 'kompleks',
                 'hulgaliselt', 'universaalne', 'tsitaat', 'tirima', 'seelik', 'sagedasem', 'otsekohe', 'lõke',
                 'filosoofia', 'fenomen', 'aitäh', 'pressima', 'paiknev', 'nõrkus', 'lavastama', 'koorem', 'jõudlus',
                 'elulugu', 'venitama', 'taldrik', 'operaator', 'inglane', 'imago', 'vanune', 'südamepuudulikkus',
                 'ratsioon', 'nakatuma', 'kiirelt', 'õiglus', 'pill', 'niiskus', 'lähtuv', 'külvama', 'alasti', 'tõhus',
                 'rahuldamine', 'külastaja', 'disain', 'avaldamine', 'tugevdama', 'terasaak', 'sile', 'seonduma',
                 'korduma', 'kaudselt', 'istutama', 'hingamine', 'glissando', 'eeter', 'bakter', 'äratundmine', 'varu',
                 'sõltuv', 'pooldama', 'levitama', 'korrektne', 'õping', 'toitaine', 'tehnoloogiline', 'moraal',
                 'konstruktsioon', 'kodumaine', 'kinnisvara', 'ideaalne', 'ümmargune', 'ülesehitus', 'väljastama',
                 'tööhõive', 'suuline', 'surnuaed', 'pikendama', 'laiemalt', 'kaer', 'vallutama', 'teesklema', 'pinnas',
                 'peetav', 'mujale', 'likvideerima', 'lahke', 'kubermang', 'kate', 'boss', 'vargus', 'valdus', 'kiir',
                 'kergitama', 'keelejuht', 'jätkamine', 'jäme', 'tervishoiuteenus', 'sööstma', 'salaja', 'romantiline',
                 'paiskama', 'orienteerima', 'kõrgele', 'edukus', 'viisakas', 'vali', 'vaht', 'potentsiaal', 'jalga',
                 'irvitama', 'vaatamine', 'loode', 'leibkond', 'kulm', 'kaader', 'dünaamika', 'astumine', 'video',
                 'veerema', 'seotus', 'omav', 'omand', 'igavesti', 'taksojuht', 'süsteemne', 'staar', 'nägemine',
                 'lähedale', 'manner', 'lõhnama', 'kodakondsus', 'sotsiaaltöötaja', 'senini', 'sarv', 'matus',
                 'läbimõõt', 'käsitlev', 'konsultatsioon', 'tõlkimine', 'tsivilisatsioon', 'trükk', 'rääkimine', 'pää',
                 'maksumaksja', 'liig', 'küngas', 'kõrts', 'huvitavam', 'hooletus', 'ehe', 'aastapäev', 'äkitselt',
                 'vastamine', 'siseministeerium', 'päevane', 'peegelduma', 'maanduma', 'kere', 'keeld', 'õppematerjal',
                 'standardsort', 'sentimeeter', 'rõivas', 'padi', 'kirjutaja', 'kahtlustatav', 'jätmine', 'järeltest',
                 'hoov', 'autoriteet', 'arvestatav', 'värviline', 'vaimustus', 'vaatleja', 'seesugune', 'lihtsustama',
                 'lemmik', 'küündima', 'intensiivne', 'asula', 'õpitulemus', 'vedelik', 'tereese', 'olgugi',
                 'mõistatus', 'katastroof', 'karu', 'vastas', 'vabastamine', 'tublisti', 'tihedus', 'tasumine',
                 'sammuma', 'pääsemine', 'postmodernne', 'papa', 'kirves', 'kaval', 'kahekordne', 'kaevama', 'toona',
                 'sulgemine', 'siseminister', 'ränk', 'raiskama', 'loominguline', 'likvideerimine', 'keskaeg', 'toetav',
                 'selliselt', 'pakkima', 'kõnealune', 'kestev', 'kaugem', 'jõulud', 'avar', 'põhimõtteline', 'pelgalt',
                 'peatoimetaja', 'palkama', 'nähtamatu', 'kukk', 'haldamine', 'ralli', 'pahandama', 'nõid', 'maasikas',
                 'laialt', 'kõri', 'juust', 'juhis', 'ülekaal', 'truu', 'skandaal', 'põhikiri', 'ost', 'majapidamine',
                 'kogumik', 'insener', 'ehmatama', 'üheselt', 'valve', 'põrsas', 'pale', 'nafta', 'kahjulik',
                 'helisema', 'graafika', 'valmisolek', 'tuhk', 'osavõtt', 'olümpiamängud', 'metsik', 'läbiv',
                 'küsitlema', 'kinnine', 'kauaks', 'kaksteist', 'distants', 'üllatav', 'taganema', 'sööde', 'saatmine',
                 'mõneti', 'koolitama', 'keeleline', 'kaubamärk', 'varvas', 'vaheaeg', 'legend', 'keerukus', 'järg',
                 'varakult', 'toonane', 'tilluke', 'teadlikult', 'pettus', 'paigaldama', 'nihkuma', 'kõrgemale',
                 'kognitiivne', 'kanduma', 'asjalik', 'üksindus', 'vaste', 'vaip', 'tagastama', 'perekonnanimi', 'niit',
                 'miilits', 'album', 'abinõu', 'roosa', 'loovutama', 'linaõli', 'kümnend', 'arutlus', 'alternatiivne',
                 'vabanemine', 'uskumatu', 'tähtsaim', 'tragöödia', 'selgem', 'rohkesti', 'nael', 'maavanem', 'kartus',
                 'kaalutlus', 'hädavajalik', 'üllatuma', 'vägev', 'tuum', 'tunnustamine', 'teisisõnu', 'tassima',
                 'tarbima', 'retseptor', 'käsutus', 'konstrueerima', 'kamp', 'jänes', 'alandama', 'vähemasti',
                 'testima', 'lint', 'füsioloogiline', 'vagun', 'poolik', 'omapärane', 'lehvitama', 'laulmine',
                 'lakkama', 'garanteerima', 'avalikustama', 'ühtlane', 'vastutav', 'vasikas', 'töötlus', 'tänulik',
                 'rivi', 'populaarsus', 'neer', 'nakatumine', 'kliinik', 'erakorraline', 'sootuks', 'poolfinaal',
                 'olenevalt', 'hüüatama', 'huviline', 'eetika', 'uurimistulemus', 'tühistama', 'sõiduauto',
                 'suursaadik', 'molekul', 'mall', 'leevendama', 'kummardama', 'alluv', 'veerg', 'tont', 'sisemus',
                 'rõdu', 'rott', 'pärinev', 'peavalu', 'nõutav', 'kohtuasi', 'hiinlane', 'varisema', 'rahuldav',
                 'pudenema', 'mistahes', 'kunstiline', 'juurdepääs', 'etteheide', 'viisteist', 'viik', 'tsoon', 'trend',
                 'sõitja', 'rahandusministeerium', 'pettumus', 'peasekretär', 'muulane', 'maksimaalselt', 'magamistuba',
                 'lähiaeg', 'ingliskeelne', 'esivanem', 'eeskiri', 'õigusnorm', 'väetis', 'vare', 'tervislik',
                 'tarvitsema', 'särav', 'sekkumine', 'pott', 'pliit', 'käimine', 'ühendamine', 'sõnnik', 'nukk',
                 'metall', 'maavalitsus', 'koobas', 'kepp', 'ebamäärane', 'ühtaegu', 'ühik', 'vanim', 'tulija',
                 'osariik', 'mustlane', 'missioon', 'matemaatiline', 'lühiajaline', 'loomaaed', 'lift', 'kett',
                 'esindus', 'apteek', 'uudishimu', 'protest', 'peaasi', 'kaasus', 'hiline', 'esitlema', 'arendaja',
                 'võistkond', 'tänaseni', 'nimeline', 'mõjur', 'käiv', 'fraas', 'tihtipeale', 'solvama', 'saaja',
                 'päevakord', 'originaal', 'olevik', 'ohutu', 'karp', 'kajastuma', 'üksteist', 'väljaselgitamine',
                 'teravili', 'rist', 'prints', 'nisu', 'mõjutav', 'köitma', 'komitee', 'kauplema', 'tööpuudus',
                 'sõnavara', 'silmapilk', 'seisukord', 'salapärane', 'pealtvaataja', 'mesilane', 'jahimees', 'eluviis',
                 'edastamine', 'eakas', 'väsimus', 'tutvus', 'sünge', 'säästma', 'start', 'raskelt', 'puruks',
                 'meeletu', 'hävima', 'arvelt', 'tundmine', 'sammas', 'pesu', 'kohutavalt', 'kaitseliit', 'järjestus',
                 'fail', 'sülitama', 'normatiivne', 'erakordselt', 'eksimus', 'assotsiatsioon', 'akadeemia',
                 'õppeaasta', 'vaatepunkt', 'tarvitamine', 'sitt', 'rabama', 'paljastama', 'mesimurakas', 'laktatsioon',
                 'kohane', 'juurdumine', 'integreerima', 'iganes', 'ebaseaduslik', 'avarii', 'võrgustik', 'vihjama',
                 'täituma', 'rahunema', 'kujutis', 'kontrollrühm', 'kompromiss', 'kaine', 'antioksüdant', 'üleüldse',
                 'soovija', 'poetama', 'pindala', 'omaaegne', 'mõningane', 'küüs', 'käsivars', 'kohanema', 'emis',
                 'diagnostika', 'vabatahtlikult', 'traagiline', 'sürjan', 'raviasutus', 'paavst', 'org', 'mõeldav',
                 'intress', 'töötus', 'sekundaarne', 'lahku', 'adekvaatne', 'õhtuti', 'vaesus', 'turvamees', 'supp',
                 'kokkupõrge', 'kaev', 'juurduma', 'illusioon', 'igatsus', 'hiljutine', 'arvestamine', 'ükskõikne',
                 'õiguskord', 'viipama', 'sõrmus', 'seeria', 'laius', 'kitsam', 'geograafiline', 'asutaja', 'üldisem',
                 'vahetamine', 'piinama', 'elamus', 'väärikas', 'varahommik', 'stuudio', 'pressikonverents',
                 'käivituma', 'kiip', 'juhend', 'inflatsioon', 'eluiga', 'vähk', 'vastuseis', 'sfäär', 'nihutama',
                 'korrastama', 'inetu', 'graafik', 'efektiivsem', 'üheaegselt', 'vehkima', 'valla', 'vaatenurk',
                 'raskendama', 'raport', 'raekoda', 'psüühiline', 'pedagoog', 'kristlane', 'tiim', 'telekanal',
                 'tasane', 'peit', 'mujalt', 'haru', 'ületamine', 'sõnavorm', 'suurepäraselt', 'seadusandja', 'sahtel',
                 'reisima', 'kohendama', 'hingamistee', 'eristuma', 'välismaine', 'tüütu', 'rohke', 'riivama',
                 'provints', 'laadima', 'kalmistu', 'iialgi', 'galerii', 'eemaldamine', 'ühispank', 'üheskoos',
                 'viisirida', 'vastupanu', 'uppuma', 'trenn', 'setu', 'sellegipoolest', 'lennuväli', 'korvpall',
                 'kirju', 'jõuline', 'ingel', 'hiiglaslik', 'higi', 'haigusjuht', 'delegatsioon', 'algne', 'salgama',
                 'rahvaluule', 'opereerima', 'kõnelus', 'kõhklema', 'hammustama', 'esteetiline', 'üldistus',
                 'surnukeha', 'põrkama', 'mask', 'lesk', 'käsitama', 'hüvasti', 'haavama', 'tuvastamine', 'päevik',
                 'okupatsioon', 'nähtavale', 'mööbel', 'libistama', 'kuulumine', 'iseseisvalt', 'ilusti', 'hoop',
                 'aktsionär', 'tarduma', 'päring', 'piiramine', 'mõtteviis', 'miskipärast', 'lips', 'hõõruma', 'eluaeg',
                 'tõusev', 'sõjaväelane', 'sobivus', 'riigipea', 'kook', 'ebaõnnestuma', 'arvukas', 'ülekanne',
                 'vastuoluline', 'vabandus', 'seen', 'seadusandlus', 'ott', 'müra', 'kiirendama', 'jõustuma', 'alane',
                 'üldsegi', 'tellija', 'sõnastus', 'suguvõsa', 'silmapiir', 'siiras', 'peatselt', 'palav', 'napilt',
                 'lihakeha', 'kohandama', 'kliinikum', 'kirurgiline', 'antibiootikum', 'ajutiselt', 'ülal', 'õudus',
                 'õitsema', 'rõõmsalt', 'pühenduma', 'pääs', 'nauding', 'lokaalne', 'kohaldama', 'kandmine',
                 'vihastama', 'vahepealne', 'tähelepanek', 'sertifikaat', 'sade', 'rangelt', 'rahustama', 'puudulik',
                 'pildistama', 'perse', 'neid', 'miinus', 'ilmalik', 'hoiatus', 'eemalduma', 'asenduma', 'valguma',
                 'toetaja', 'tempel', 'põhikool', 'närviline', 'närima', 'needma', 'mitmekesisus', 'marssima',
                 'lahutus', 'kahjum', 'instrument', 'elutuba', 'eales', 'võitleja', 'tööriist', 'tõestus', 'tugitool',
                 'suuteline', 'solvuma', 'putukas', 'pluus', 'piimatoodang', 'peatus', 'kunstlik', 'domineeriv',
                 'toimik', 'roos', 'kostüüm', 'iseäranis', 'hiljemalt', 'süüdlane', 'stipendium', 'röövel', 'rock',
                 'primaarne', 'metafoor', 'kinnitamine', 'kaugemal', 'inhibiitor', 'fotograaf', 'ühte', 'virtuaalne',
                 'töösuhe', 'tuntum', 'soovitav', 'ristmik', 'riigivõim', 'psühholoogia', 'paratamatu', 'neeger',
                 'kvalitatiivne', 'kuuluvus', 'kraam', 'keskpank', 'hüvitama', 'teisene', 'lävi', 'käsitsi',
                 'kuninganna', 'kraav', 'kont', 'doktoritöö', 'õhtusöök', 'väljaandmine', 'visuaalne', 'transport',
                 'prügikast', 'palavik', 'mõrv', 'mahukas', 'magister', 'lage', 'küün', 'kaunistama', 'kasvaja',
                 'kaenal', 'välisriik', 'võimekus', 'valimisliit', 'tige', 'räpane', 'pomm', 'piki', 'küps',
                 'kuivatama', 'kaar', 'jalakäija', 'esik', 'andmestik', 'vanur', 'seiklus', 'sedasi', 'riigiasutus',
                 'raisk', 'puhtalt', 'positiivselt', 'lits', 'kõhn', 'kaitseminister', 'ettekirjutus', 'deklaratsioon',
                 'arvukus', 'süttima', 'sõlm', 'purunema', 'osake', 'loopima', 'lineaarne', 'filosoofiline', 'elamu',
                 'bilanss', 'asumine', 'akadeemiliselt', 'ait', 'ümbrik', 'värvus', 'tarvilik', 'puiestee', 'murduma',
                 'igasugu', 'bensiin', 'väärtushinnang', 'varieeruvus', 'töörühm', 'traditsiooniliselt', 'toimumine',
                 'rüütel', 'põud', 'paralleel', 'motivatsioon', 'leiutama', 'kits', 'kibe', 'karv', 'etendama',
                 'bassein', 'analoogiline', 'üllatavalt', 'see-eest', 'raskesti', 'ooper', 'laiendamine',
                 'kompenseerima', 'järk', 'joodik', 'hüve', 'britt', 'tühjus', 'pauk', 'pakkuv', 'nukker', 'massiline',
                 'lootusetu', 'koolimaja', 'keskaegne', 'keerukam', 'imestus', 'õppeasutus', 'veresoon', 'rajoon',
                 'müümine', 'käsutama', 'kuritegevus', 'kiruma', 'kamber', 'filosoof', 'edaspidine', 'allutama',
                 'vananema', 'tervelt', 'temaatika', 'pooldaja', 'natukene', 'esmapilk', 'töötasu', 'rakendatav',
                 'parempoolne', 'orkester', 'mehaaniline', 'madu', 'konjak', 'keerlema', 'järelduma', 'hapnik',
                 'ühendav', 'väljapääs', 'tulem', 'tippkohtumine', 'sõimama', 'struktuurne', 'režiim', 'põhjalikumalt',
                 'olulisim', 'märkamatult', 'lõppemine', 'lobisema', 'komöödia', 'komimaa', 'kodulehekülg', 'kiirgus',
                 'diplomaat', 'tähelepanuväärne', 'toll', 'talunik', 'sõdima', 'ruut', 'retsept', 'omadussõna', 'mess',
                 'klassifikatsioon', 'heameel', 'enesetapp', 'üksikasi', 'ühene', 'tsaar', 'suurriik', 'saatuslik',
                 'regulaarselt', 'organisatsiooniline', 'lähedalt', 'luik', 'käratama', 'keskealine', 'inspektor',
                 'infoühiskond', 'ikoon', 'assistent', 'agentuur', 'ülim', 'ühtsus', 'õudne', 'tõttama', 'teenindamine',
                 'seaduspärasus', 'samalaadne', 'reklaamima', 'nähtuma', 'niitma', 'lõbu', 'kõnnitee', 'kuuldav',
                 'kujundus', 'kadu', 'edendamine', 'avastus', 'analoogne', 'viimine', 'uskumus', 'tõlkija', 'trepikoda',
                 'sümboolne', 'sperma', 'puus', 'pidi', 'pakett', 'märge', 'muutumatu', 'laup', 'lahe', 'klaver',
                 'gramm', 'eit', 'üht-teist', 'õlleoder', 'viltu', 'rase', 'paarsada', 'mikroobne', 'kateeder',
                 'kasvuhoone', 'kasutuselevõtt', 'episood', 'vasakule', 'tähistamine', 'telk', 'sagedane', 'papp',
                 'paanika', 'nool', 'kvantitatiivne', 'kasvataja', 'interpretatsioon', 'õhkkond', 'žanr', 'surnud',
                 'soosima', 'lähemal', 'loosung', 'kirikuseadus', 'essee', 'ärritama', 'teenindama', 'poeet', 'muru',
                 'maakoor', 'lõhki', 'kõrgel', 'kuumus', 'koostaja', 'ümbert', 'regulaarne', 'neutraalne', 'nakkus',
                 'kuub', 'kese', 'kaasamine', 'hukka', 'hinnatõus', 'heinamaa', 'era', 'ühiselamu', 'vägisi',
                 'võimalikkus', 'toel', 'teoreetiliselt', 'tegevusala', 'punker', 'meelelahutus', 'küljest',
                 'kukkumine', 'kataloog', 'juurdekasv', 'imeline', 'hõljuma', 'hirmutama', 'edasi-tagasi', 'vann',
                 'vahimees', 'usaldusväärsus', 'takt', 'säär', 'parata', 'ostujõupariteet', 'liiklusõnnetus',
                 'kompleksne', 'kihelkond', 'järeltulija', 'jaht', 'hunnik', 'headus', 'esindusorgan', 'ehitaja',
                 'aegu', 'ülespoole', 'teenija', 'põhjuslik', 'meenutav', 'maksev', 'kestel', 'karistusõigus', 'hõbe',
                 'andestama', 'alam', 'vallavalitsus', 'vaesem', 'tosin', 'teadustöö', 'teaduskond', 'plahvatama',
                 'märkimisväärselt', 'küüditamine', 'kindlam', 'kaheksas', 'juurutamine', 'hõre', 'vöö', 'trikk',
                 'tehnikaülikool', 'sooritamine', 'rikastama', 'pliiats', 'nõuanne', 'läikiv', 'kokkuhoid', 'esitaja',
                 'eluaegne', 'edenema', 'diskursus', 'abort', 'unikaalne', 'püstol', 'pintsak', 'osavõtja', 'nihe',
                 'lõpptulemus', 'liitlane', 'konkureerima', 'hääldus', 'haldus', 'füüsiliselt', 'finantseerimine',
                 'enesetunne', 'elukutse', 'ekspertiis', 'aminohape', 'toonitama', 'tilk', 'tablett', 'soodustus',
                 'seik', 'ristik', 'produtsent', 'nöör', 'lõpetus', 'keskkonnakaitse', 'kantsler', 'kaitsepolitsei',
                 'hämarus', 'anne', 'ülemaailmne', 'vääriline', 'veelkord', 'tutvustamine', 'puur', 'preili',
                 'passiivne', 'laik', 'laialdane', 'kõrvaltoime', 'kaitseministeerium', 'järgimine', 'ihkama', 'habras',
                 'ammoniaak', 'vahva', 'tüsistus', 'tervitus', 'tegevdirektor', 'tamm', 'südametunnistus', 'sperm',
                 'portfell', 'peletama', 'paisuma', 'maaelu', 'lõhe', 'kõrvaline', 'imema', 'erakordne', 'võõrkeel',
                 'täiendus', 'tootlikkus', 'sõltumatus', 'sponsor', 'portree', 'peenike', 'parras', 'niikaua', 'istuv',
                 'igapäevaelu', 'elukaaslane', 'üldsus', 'võlgu', 'traat', 'tagune', 'segment', 'sai', 'rikkam',
                 'riietus', 'reaalselt', 'isu', 'eelkäija', 'analüütik', 'õigussüsteem', 'väljanägemine', 'tööaeg',
                 'teismeline', 'plakat', 'nõudev', 'kraniaalne', 'konsonant', 'karvane', 'eluruum', 'õmblema',
                 'varustus', 'varjus', 'toomine', 'suunamine', 'rüütelkond', 'ringkonnakohus', 'oo', 'kollektiiv',
                 'kinnistu', 'karjatama', 'isamaa', 'diabeet', 'väljendus', 'vajav', 'tagumik', 'põlev', 'piloot',
                 'motiveerima', 'mismoodi', 'liigitama', 'kükitama', 'kroonine', 'koondamine', 'kangesti',
                 'haigestumus', 'erastama', 'avaldumine', 'autoriõigus', 'välisuks', 'vähesus', 'vastne', 'vastanduma',
                 'turumajandus', 'tohter', 'spetsiaalselt', 'soetama', 'roog', 'religioosne', 'pooleks', 'paigal',
                 'maksejõuetus', 'maakohus', 'kristlus', 'komplekt', 'kavandatav', 'kalju', 'kalender', 'iroonia',
                 'identifitseerima', 'hierarhia', 'harjutus', 'garantii', 'euroliit', 'eraisik', 'ajajärk', 'valvur',
                 'vaheldus', 'tallinlane', 'stereotüüp', 'soovitatav', 'sisestama', 'reguleerimine', 'nüi', 'julm',
                 'jaguma', 'funktsionaalsus', 'ajalooõpetaja', 'ümbruskond', 'ähvardus', 'välk', 'võsa', 'viibimine',
                 'vasakpoolne', 'täiuslik', 'teadmatus', 'põhjalikum', 'puistama', 'münt', 'läikima', 'kordus',
                 'konservatiivne', 'kirst', 'kehvem', 'kehamass', 'kaalium', 'jooksev', 'elumaja', 'eksemplar',
                 'väljapoole', 'usklik', 'säilimine', 'soojem', 'soodsam', 'linnakohus', 'libe', 'kurbus', 'kommunism',
                 'kehtivus', 'jätkuv', 'jumalik', 'itaallane', 'ühisus', 'õigusvastane', 'tikk', 'tajutav', 'põrutama',
                 'nii-öelda', 'mootorratas', 'kompensatsioon', 'karjalane', 'jutuajamine', 'hiljaks', 'ensüüm',
                 'ammune', 'aklimatiseerumine', 'viisakalt', 'usutavalt', 'tunnel', 'ründaja', 'rebane', 'passima',
                 'mõrtsukas', 'leitnant', 'küünarnukk', 'kirjanduslugu', 'jäätis', 'illustreerima', 'elulaad', 'ammugi',
                 'aastaaeg', 'üldjoon', 'ühendriik', 'sõnapaar', 'saatan', 'ratsionaalne', 'pritsima', 'palee',
                 'lipiid', 'hääldama', 'arusaamatus', 'arenev', 'üür', 'vanuserühm', 'ringkond', 'riigiametnik',
                 'rahutu', 'pikkamisi', 'levitamine', 'küsitav', 'kohalt', 'kaubandus', 'jäämine', 'hüpertensioon',
                 'öösiti', 'vaikimine', 'vahetevahel', 'rumalus', 'rahulolematus', 'rabelema', 'põgenemine',
                 'pereliige', 'itsitama', 'genereerima', 'entiteet', 'tõekspidamine', 'sisend', 'sihtima',
                 'regionaalne', 'põlvili', 'põlgama', 'põhiõigus', 'mõjuv', 'kolledž', 'kaaren', 'joomine', 'halvenema',
                 'eliit', 'üksmeel', 'ühiselt', 'ööbima', 'tänini', 'trauma', 'tegelemine', 'tasuline', 'tahtlik',
                 'seltsing', 'rahvaliit', 'pätt', 'pärani', 'pronoomen', 'piirivalve', 'narkomaan', 'kooselu',
                 'kallistama', 'isiksuseomadus', 'igaveseks', 'ettevaatus', 'eirama', 'arvustus', 'väljaõpe',
                 'vaidlustama', 'tõstatama', 'trügima', 'tasakesi', 'saksakeelne', 'moodustumine', 'küllaldane',
                 'islam', 'hankimine', 'eeltoodud', 'eelpool', 'asfalt', 'vangutama', 'universum', 'sotsialistlik',
                 'rannik', 'näit', 'meesterahvas', 'kompanii', 'kannul', 'hukkunu', 'eemalt', 'arteriaalne', 'võidu',
                 'toimepanija', 'tasakaalustama', 'sportlik', 'ristima', 'mõtisklema', 'mullikas', 'mahl', 'kättemaks',
                 'kärbes', 'katserühm', 'eriliselt', 'ebaoluline', 'talvine', 'suisa', 'pahane', 'mikroorganism',
                 'kuulatama', 'kusagile', 'jäik', 'jaotamine', 'cit', 'akadeemik', 'välispoliitika', 'võrdsus',
                 'valitsemine', 'tobe', 'tahtmatult', 'populatsioon', 'normaalselt', 'monoloog', 'meloodia', 'major',
                 'magneesiumisisaldus', 'laisk', 'kaastunne', 'julge', 'hülgama', 'grammatiline', 'esineja',
                 'tundlikkus', 'otsustavalt', 'naeruväärne', 'maailmavaade', 'laotama', 'koda', 'kantselei', 'kampsun',
                 'ausus', 'asjakohane', 'ulatuv', 'uinuma', 'tulemuslikkus', 'rituaal', 'puudujääk', 'poolsaar',
                 'pooleldi', 'pankreatiit', 'meelsasti', 'kurjus', 'kindlustamine', 'kellaaeg', 'karikas', 'kand',
                 'foon', 'arukas', 'ütlemine', 'tolleaegne', 'terminoloogia', 'talumees', 'tall', 'sisendama',
                 'ruumiline', 'osutaja', 'nutt', 'mugul', 'koosmõju', 'katk', 'kastma', 'järjepidevus', 'import',
                 'ilmselgelt', 'idioot', 'harv', 'vältimatu', 'vähemus', 'võileib', 'veoauto', 'vastuvõetav', 'vaevu',
                 'tarvik', 'taotlemine', 'suvila', 'rahandusminister', 'põlevkivi', 'poolne', 'parun', 'olevus',
                 'mängimine', 'linlane', 'laiutama', 'küpsetama', 'käsiraamat', 'juhendama', 'enesekindlus',
                 'aseesimees', 'allkirjastama', 'agressiivne', 'väliselt', 'tähelepanelikult', 'soliidne', 'ringis',
                 'pits', 'operatsioonisüsteem', 'mart', 'maksukohustuslane', 'juhitav', 'etteaste', 'avatus', 'antav',
                 'anonüümne', 'ühestamine', 'vahemaa', 'toimunu', 'teravalt', 'teadaolev', 'sestap', 'regi', 'rahutus',
                 'presidendivalimine', 'peopesa', 'paremale', 'parandus', 'pahandus', 'niinimetatud', 'modelleerimine',
                 'lähtekoht', 'kohtupraktika', 'kassa', 'karakter', 'automaatne'];
