version: "3.7"

services:
  postgres:
    image: postgres:13-alpine
    container_name: evkk-postgres
    deploy:
      restart_policy:
        condition: any
        window: 120s
    secrets:
      - EVKK_DB_DATASOURCE_PASSWORD
    environment:
      POSTGRES_USER: db_user
      POSTGRES_DB: evkk
      POSTGRES_PASSWORD_FILE: /run/secrets/EVKK_DB_DATASOURCE_PASSWORD
    volumes:
      - /srv/evkk/data/postgres:/var/lib/postgresql/data
