version: "3.7"

services:
  redis:
    image: redis:6-alpine
    container_name: evkk-redis
    restart: always
    volumes:
      - /srv/evkk/data/redis:/data

  caddy:
    image: caddy:2.8.4-alpine
    container_name: evkk-caddy
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - $PWD/compose/Caddyfile:/etc/caddy/Caddyfile

  ui:
    image: evkk-ui
    container_name: evkk-ui
    restart: always
    depends_on:
      - api

  api:
    image: evkk-backend
    container_name: evkk-api
    restart: always
    entrypoint: [ "/bin/bash", "-c", "java -jar app/api.jar" ]
    secrets:
      - EVKK_API_DATASOURCE_PASSWORD
      - HARID_CLIENT_ID
      - HARID_CLIENT_SECRET
      - JWT_TOKEN_SECRET
    depends_on:
      - postgres
      - redis
    env_file:
      - $PWD/conf/common.env
      - $PWD/conf/api.env

  task_scheduler:
    image: evkk-backend
    container_name: evkk-task-scheduler
    restart: always
    entrypoint: [ "/bin/bash", "-c", "java -jar app/task-scheduler.jar" ]
    secrets:
      - EVKK_TASK_SCHEDULER_DATASOURCE_PASSWORD
    depends_on:
      - postgres
    env_file:
      - $PWD/conf/common.env
      - $PWD/conf/task-scheduler.env

  stanza-server:
    image: evkk-stanza-server
    container_name: evkk-stanza-server
    restart: always
    environment:
      - CPU_CORE={{.Task.Slot}}
    deploy:
      mode: replicated
      replicas: 5
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
      update_config:
        parallelism: 1
        order: start-first

  corrector-server:
    image: evkk-corrector-server
    container_name: evkk-corrector-server
    restart: always
    deploy:
      resources:
        limits:
          memory: 15G

  grammar-worker-server:
    image: grammar-worker-server
    container_name: grammar-worker-server
    restart: always
    deploy:
      resources:
        limits:
          memory: 25G

  klasterdaja:
    image: evkk-klasterdaja
    container_name: evkk-klasterdaja
    restart: always

  clusterfinder:
    image: evkk-backend
    container_name: evkk-clusterfinder
    restart: always
    entrypoint: [ "/bin/bash", "-c", "java -jar app/clusterfinder.jar" ]
    env_file:
      - $PWD/conf/common.env
      - $PWD/conf/clusterfinder.env
