version: "3.7"

services:

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: db_user
      POSTGRES_DB: evkk
    env_file:
      - conf/local_db.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    volumes:
      - ./data/redis:/data

  ui:
    image: evkk-ui

  caddy:
    image: caddy:2.4.5-alpine
    restart: unless-stopped
    ports:
      - "9999:9999"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile

  db:
    image: evkk-backend
    entrypoint: [ "/bin/bash", "-c", "java -jar app/db.jar" ]
    restart: on-failure
    env_file:
      - conf/local_common.env
      - conf/local_db.env
      - conf/local_api.env
    depends_on:
      - postgres

  api:
    image: evkk-backend
    entrypoint: [ "/bin/bash", "-c", "java -jar app/api.jar" ]
    env_file:
      - conf/local_common.env
      - conf/local_api.env
    depends_on:
      - db
      - redis
