version: "3.7"

services:
  db:
    image: evkk-backend
    entrypoint: [ "/bin/bash", "-c", "java -jar app/db.jar" ]
    secrets:
      - EVKK_DB_DATASOURCE_PASSWORD
      - EVKK_BACKUP_DATASOURCE_PASSWORD
      - EVKK_API_DATASOURCE_PASSWORD
    env_file:
      - $PWD/conf/common.env
      - $PWD/conf/db.env
      - $PWD/conf/api.env
    depends_on:
      - postgres
