version: "3.7"

services:

  redis:
    image: redis:6-alpine
    container_name: evkk-redis
    restart: always
    volumes:
      - /srv/evkk/data/redis:/data

  caddy:
    image: caddy:2.4.5-alpine
    container_name: evkk-caddy
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - $PWD/compose/Caddyfile:/etc/caddy/Caddyfile

  ui:
    image: evkk-ui
    container_name: evkk-ui
    restart: always
    depends_on:
      - api

  api:
    image: evkk-backend
    container_name: evkk-api
    restart: always
    entrypoint: [ "/bin/bash", "-c", "java -jar app/api.jar" ]
    secrets:
      - EVKK_API_DATASOURCE_PASSWORD
    depends_on:
      - postgres
      - redis
    env_file:
      - $PWD/conf/common.env
      - $PWD/conf/api.env

  task_scheduler:
    image: evkk-backend
    container_name: evkk-task-scheduer
    restart: always
    entrypoint: [ "/bin/bash", "-c", "java -jar app/task-scheduler.jar" ]
    secrets:
      - EVKK_TASK_SCHEDULER_DATASOURCE_PASSWORD
    depends_on:
      - postgres
    env_file:
      - $PWD/conf/common.env
      - $PWD/conf/task-scheduler.env

  stanza-server:
    image: evkk-stanza-server
    container_name: evkk-stanza-server
    restart: always
    deploy:
      resources:
        limits:
          memory: 8G

  corrector-server:
    image: evkk-corrector-server
    container_name: evkk-corrector-server
    restart: always
    deploy:
      resources:
        limits:
          memory: 4G

  klasterdaja:
    image: evkk-klasterdaja
    container_name: evkk-klasterdaja
    restart: always

  clusterfinder:
    image: evkk-backend
    container_name: evkk-clusterfinder
    restart: always
    entrypoint: [ "/bin/bash", "-c", "java -jar app/clusterfinder.jar" ]
    env_file:
      - $PWD/conf/common.env
      - $PWD/conf/clusterfinder.env
