version: "3.7"

services:

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: db_user
      POSTGRES_DB: evkk
    env_file:
      - $PWD/conf/db.env
    volumes:
      - $PWD/data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    volumes:
      - $PWD/data/redis:/data

  ui:
    image: evkk-ui

  caddy:
    image: caddy:2.4.5-alpine
    restart: unless-stopped
    ports:
      - "9999:9999"
    volumes:
      - $PWD/compose/Caddyfile:/etc/caddy/Caddyfile

  db:
    image: evkk-backend
    entrypoint: [ "/bin/bash", "-c", "java -jar app/db.jar" ]
    env_file:
      - $PWD/conf/common.env
      - $PWD/conf/db.env
      - $PWD/conf/api.env
    depends_on:
      - postgres

  api:
    image: evkk-backend
    entrypoint: [ "/bin/bash", "-c", "java -jar app/api.jar" ]
    env_file:
      - $PWD/conf/common.env
      - $PWD/conf/api.env
    depends_on:
      - db
      - redis
