version: "3.7"

services:

  redis:
    image: redis:6-alpine
    container_name: evkk-redis
    restart: always
    volumes:
      - /srv/evkk/data/redis:/data

  caddy:
    image: caddy:2.4.5-alpine
    container_name: evkk-caddy
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - $PWD/compose/Caddyfile:/etc/caddy/Caddyfile

  ui:
    image: evkk-ui
    container_name: evkk-ui
    restart: always
    depends_on:
      - api

  sonarakendus:
    image: evkk-sonarakendus
    container_name: evkk-sonarakendus
    restart: always

  api:
    image: evkk-backend
    container_name: evkk-api
    restart: always
    entrypoint: [ "/bin/bash", "-c", "java -jar app/api.jar" ]
    secrets:
      - EVKK_API_DATASOURCE_PASSWORD
    depends_on:
      - postgres
      - redis
    env_file:
      - $PWD/conf/common.env
      - $PWD/conf/api.env

  stanza:
    image: evkk-stanza
    container_name: evkk-stanza
    restart: always

  #clusterfinder:
  #  image: evkk-backend
  #  restart: always
  #  entrypoint: [ "/bin/bash", "-c", "java -jar app/clusterfinder.jar" ]
  #  env_file:
  #    - $PWD/conf/common.env
  #    - $PWD/conf/clusterfinder.env
  #  depends_on:
  #    - api
